### ISSUE TITLE
Results page height

### ISSUE THREAD

**Issue by austinbuckler** [austinbuckler/bubblr#2]
The height of the results container needs to be fixed. As it stands it is now `margin-top: 100%` unsure if that will actually fix the problem.

**Comment by dparkd** [comment]
What's the issue with the results container? I don't see any issues

**Comment by austinbuckler** [comment]
If you inspect the html and duplicate one of the result sets. You will see that the twitter results go way up the page.

**Comment by austinbuckler** [comment]
Found the fix.
